name: CI
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  change-detection:
    uses: ./.github/workflows/reusable-change-detection.yml

  cpp-tests:
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    uses: ./.github/workflows/reusable-cpp-ci.yml
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}

  cpp-linter:
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-linter)
    uses: ./.github/workflows/reusable-cpp-linter.yml

  python-tests:
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    uses: ./.github/workflows/reusable-python-ci.yml
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}

  code-ql:
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-code-ql)
    uses: ./.github/workflows/reusable-code-ql.yml

  required-checks-pass: # This job does nothing and is only used for branch protection
    if: always()
    needs:
      - change-detection
      - cpp-tests
      - cpp-linter
      - python-tests
      - code-ql
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: >-
            ${{
              fromJSON(needs.change-detection.outputs.run-cpp-tests)
              && '' || 'cpp-tests,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-cpp-linter)
              && '' || 'cpp-linter,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-python-tests)
              && '' || 'python-tests,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-code-ql)
              && '' || 'code-ql,'
            }}
          jobs: ${{ toJSON(needs) }}
