name: cpp-linter

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  clang-version: 16

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    container: silkeh/clang:${{ env.clang-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate compilation database
        run: |
          export CC=clang-${{ env.clang-version }}
          export CXX=clang++-${{ env.clang-version }}
          $CC --version
          $CXX --version
          cmake -S . -B build

      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ""
          tidy-checks: ""
          version: ${{ env.clang-version }}
          ignore: build
          thread-comments: true
          step-summary: true
          database: "build"
          extra-args: -std=c++17
          files-changed-only: true

      - name: Fail if linter found errors
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Linter found errors" && exit 1
