name: 🇨‌ • CI
on:
  workflow_call:
    secrets:
      token:
        description: "The token to use for Codecov"
        required: true
    inputs:
      cmake-args:
        description: "Additional arguments to pass to CMake on every OS"
        default: ""
        type: string
      cmake-args-ubuntu:
        description: "Additional arguments to pass to CMake on Ubuntu"
        default: ""
        type: string
      cmake-args-macos:
        description: "Additional arguments to pass to CMake on macOS"
        default: ""
        type: string
      cmake-args-windows:
        description: "Additional arguments to pass to CMake on Windows"
        default: ""
        type: string

jobs:
  cpp-tests-ubuntu:
    name: 🐧 ${{ matrix.config }}
    strategy:
      matrix:
        config: [Debug, Release]
      fail-fast: false
    uses: ./.github/workflows/reusable-cpp-tests-ubuntu.yml
    with:
      config: ${{ matrix.config }}
      cmake-args: ${{ inputs.cmake-args }} ${{ inputs.cmake-args-ubuntu }}

  cpp-tests-macos:
    name: 🍎 ${{ matrix.config }}
    strategy:
      matrix:
        config: [Debug, Release]
      fail-fast: false
    uses: ./.github/workflows/reusable-cpp-tests-macos.yml
    with:
      config: ${{ matrix.config }}
      cmake-args: ${{ inputs.cmake-args }} ${{ inputs.cmake-args-macos }}

  cpp-tests-windows:
    name: 🏁 ${{ matrix.config }}
    strategy:
      matrix:
        config: [Debug, Release]
      fail-fast: false
    uses: ./.github/workflows/reusable-cpp-tests-windows.yml
    with:
      config: ${{ matrix.config }}
      cmake-args: ${{ inputs.cmake-args }} ${{ inputs.cmake-args-windows }}

  coverage:
    name: 📈
    uses: ./.github/workflows/reusable-cpp-coverage.yml
    secrets:
      token: ${{ secrets.token }}
    with:
      cmake-args: ${{ inputs.cmake-args }} ${{ inputs.cmake-args-ubuntu }}
