name: 🇨 • Lint
on:
  workflow_call:
    inputs:
      clang-version:
        description: "Clang version to use"
        default: 16
        type: number
      cmake-args:
        description: "Additional arguments to pass to CMake"
        default: ""
        type: string

jobs:
  lint:
    name: 🚨 Lint
    runs-on: ubuntu-latest
    env:
      clang-version: ${{ inputs.clang-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install clang-${{ env.clang-version }}
        run: |
          sudo apt-get update
          wget https://apt.llvm.org/llvm.sh -O ${{ runner.temp }}/llvm_install.sh
          chmod +x ${{ runner.temp }}/llvm_install.sh
          if sudo ${{ runner.temp }}/llvm_install.sh ${{ env.clang-version }}; then
            sudo apt-get install -y clang-format-${{ env.clang-version }} clang-tidy-${{ env.clang-version }} || exit 1
          else
            echo "Installation from script failed."
            exit 1
          fi
          echo "CC=clang-${{ env.clang-version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ env.clang-version }}" >> $GITHUB_ENV

      - name: Generate compilation database
        run: |
          echo $CC
          echo $CXX
          $CC --version
          $CXX --version
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug ${{ inputs.cmake-args }}

      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          style: ""
          tidy-checks: ""
          version: ${{ env.clang-version }}
          ignore: "build|include/python|src/python"
          thread-comments: true
          step-summary: true
          database: "build"
          extra-args: -std=c++17
          files-changed-only: true

      - name: Fail if linter found errors
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Linter found errors" && exit 1
