name: 🐍 • CI

on:
  workflow_call:
    secrets:
      token:
        description: "The token to use for Codecov"
        required: true
    inputs:
      setup-z3:
        description: "Whether to set up Z3"
        default: false
        type: boolean
      z3-version:
        description: "The version of Z3 to set up"
        default: "4.11.2"
        type: string

jobs:
  lint:
    name: 🚨 Lint
    uses: ./.github/workflows/reusable-python-linter.yml
    with:
      setup-z3: ${{ inputs.setup-z3 }}
      z3-version: ${{ inputs.z3-version }}

  python-tests-ubuntu:
    name: 🐧 ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    uses: ./.github/workflows/reusable-python-tests.yml
    with:
      runs-on: ubuntu-latest
      python-version: ${{ matrix.python-version }}
      setup-z3: ${{ inputs.setup-z3 }}
      z3-version: ${{ inputs.z3-version }}

  python-tests-macos:
    name: 🍎 ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.11"]
    uses: ./.github/workflows/reusable-python-tests.yml
    with:
      runs-on: macos-latest
      python-version: ${{ matrix.python-version }}
      setup-z3: ${{ inputs.setup-z3 }}
      z3-version: ${{ inputs.z3-version }}

  python-tests-windows:
    name: 🏁 ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.11"]
    uses: ./.github/workflows/reusable-python-tests.yml
    with:
      runs-on: windows-latest
      python-version: ${{ matrix.python-version }}
      setup-z3: ${{ inputs.setup-z3 }}
      z3-version: ${{ inputs.z3-version }}

  coverage:
    name: 📈 ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.11"]
    uses: ./.github/workflows/reusable-python-coverage.yml
    with:
      python-version: ${{ matrix.python-version }}
      setup-z3: ${{ inputs.setup-z3 }}
      z3-version: ${{ inputs.z3-version }}
    secrets:
      token: ${{ secrets.token }}

  dist:
    name: 📦 Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - if: ${{ inputs.setup-z3 }}
        name: Setup Z3
        uses: cda-tum/setup-z3@v1
        with:
          version: ${{ inputs.z3-version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Set up mold as linker (Linux only)
        uses: rui314/setup-mold@v1
      - uses: hynek/build-and-inspect-python-package@v1
